name: overmind-submission-run-tests
run-name: Run tests for quest submission
on:
  workflow_dispatch:
    inputs:
      secretKey:
        description: "Secret key"
        required: true
        default: "INVALID_KEY"
      questId:
        description: "questId of submission"
        required: true
      userId:
        description: "userId of submission"
        required: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: mysten/sui-services:ci # Using the Sui Node Docker image
    steps:
      - uses: actions/checkout@v3
      - name: Run sui move test
        run: sui move test
        continue-on-error: true
      - name: Call webhook
        run: |
          webhook_url="https://mod.overmind.xyz/api/handle-test-run"
          output=$(cat output.txt)
          json_payload=$(python3 -c "import json, sys; print(json.dumps({'output': sys.argv[1], 'secretKey': '${{inputs.secretKey}}', 'questId': '${{inputs.questId}}', 'userId': '${{inputs.userId}}' }))" "$output")
          curl -X POST -H "Content-Type: application/json" -d "$json_payload" "$webhook_url"
